In [1]:
import numpy as np
import numpy.linalg as linalg

### Generating a Matrix

In [2]:
A = np.matrix([[1,2], [3,4]])
A

matrix([[1, 2],
        [3, 4]])

### Inverting a Matrix

In [3]:
A_inv = linalg.inv(A)
A_inv

matrix([[-2. ,  1. ],
        [ 1.5, -0.5]])

### Multiplying Matrices

In [4]:
A*A_inv

matrix([[  1.00000000e+00,   0.00000000e+00],
        [  8.88178420e-16,   1.00000000e+00]])

### Computing Eigenvalues and Vectors

In [5]:
eigenvalues, eigenvectors = linalg.eig(A)
eigenvalues

array([-0.37228132,  5.37228132])